Observations: ['Number', 'of', 'obs', '=']
F_Stat: ['F(']
F_Prob: ['Prob', '>', 'F', '=']
R_Sqr: ['R-squared', '=']
Adj_R_Sqr: ['Adj', 'R-squared', '=']
Within_R_Sqr: ['Within', 'R-sq.']
Root_MSE: ['Root', 'MSE', '=']
Adjusted_Clusters: ['(Std.', 'Err.', 'adjusted', 'for']

OLS_Divider: ['Number', 'of', 'obs']
Summary_Divider: ['Variable', '|', 'Obs', 'Mean', 'Std.', 'Dev.', 'Min', 'Max']
Tab_Divider: ['|', 'Freq.', 'Percent', 'Cum.']

OLS_Headers: ["coefficients", "std_errs", "t_stats", "p_stats", "conf_95_min", "conf_95_max"]
Summary_Headers: ["obs", "mean", "std_dev", "min", "max"]
Tabulate_Headers: ["frequency", "percent", "cumulative"]