Observations: ['Number', 'of', 'obs', '=']
F_Stat: ['F(']
F_Prob: ['Prob', '>', 'F', '=']
R_Sqr: ['R-squared', '=']
Adj_R_Sqr: ['Adj', 'R-squared', '=']
Within_R_Sqr: ['Within', 'R-sq.']
Root_MSE: ['Root', 'MSE', '=']
Adjusted_Clusters: ['(Std.', 'Err.', 'adjusted', 'for']
FE_Within_R_Sqr: ['within', '=']
FE_Between_R_Sqr: ['between', '=']
FE_Overall_R_Sqr: ['overall', '=']
FE_Obs_Per_Group_Min: ['min', '=']
FE_Obs_Per_Group_Avg: ['avg', '=']
FE_Obs_Per_Group_Max: ['max', '=']


OLS_Divider: ['Source', '|', 'SS', 'df', 'MS', 'Number', 'of', 'obs', '=']
HDFE_Divider: ['HDFE', 'Linear', 'regression', 'Number', 'of', 'obs', '=']
Summary_Divider: ['Variable', '|', 'Obs', 'Mean', 'Std.', 'Dev.', 'Min', 'Max']
Tab_Divider: ['|', 'Freq.', 'Percent', 'Cum.']
FEWithin: ['Fixed-effects', '(within)', 'regression', 'Number', 'of', 'obs', '=']

OLS_Headers: ["coefficients", "std_errs", "t_stats", "p_stats", "conf_95_min", "conf_95_max"]
Summary_Headers: ["obs", "mean", "std_dev", "min", "max"]
Tabulate_Headers: ["frequency", "percent", "cumulative"]
